# Generated by Django 5.2.6 on 2025-11-18 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(help_text='Descrição detalhada da atração.')),
                ('horario_funcionamento', models.CharField(blank=True, max_length=200, null=True)),
                ('informacoes_entrada', models.CharField(blank=True, help_text="Ex: 'Gratuita', 'Consultar valores'.", max_length=200, null=True)),
                ('imagem', models.ImageField(help_text='Imagem principal da atração.', upload_to='atracoes/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(help_text="Ex: 'fas fa-tree'. Use classes do Font Awesome.", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='atracao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atracoes', to='crud_app.categoria'),
        ),
        migrations.AddField(
            model_name='atracao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atracoes', to='crud_app.cidade'),
        ),
    ]
