# Generated by Django 5.2.6 on 2025-11-25 23:59

import crud_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='imagem',
            field=models.ImageField(help_text='Imagem principal da atração.', upload_to=crud_app.models.atracao_image_path),
        ),
    ]
