# Generated by Django 5.2.6 on 2025-11-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_alter_atracao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='imagem',
            field=models.ImageField(help_text='Imagem principal da atração.', upload_to='atracoes/temp/'),
        ),
    ]
